### ISSUE TITLE
Adding a description of the annual processing to the Rubin Solar System Processing

### ISSUE THREAD

**Issue by mschwamb** [lsst/dp0-3_lsst_io#73]
The [new page about Solar System processing ](https://dp0-3.lsst.io/data-products-dp0-3/solar-system-processing-pipeline.html)only talks about the nightly processing that includes the MPC, but at annual data release there is also going to be processing that has the Solar System tables just that orbits are fit from Rubin data only and annual data release does not rely on association of known objects using MPC orbit predictions.  Would it be possible to add some description about the annual data release and how it is different from the nighlty Rubin Solar System Processing - thanks

**Comment by MelissaGraham** [comment]
Opened an internal work issue to explore these updates, thank you.
https://rubinobs.atlassian.net/browse/SP-1642
